# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small_game_xuanzejuese_ui.ui'
#
# Created: Fri Dec 04 17:54:36 2020
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_xuanzejuese(object):
    def setupUi(self, Form_xuanzejuese):
        Form_xuanzejuese.setObjectName(_fromUtf8("Form_xuanzejuese"))
        Form_xuanzejuese.resize(400, 300)
        Form_xuanzejuese.setMaximumSize(QtCore.QSize(400, 300))
        self.xuanze = QtGui.QPushButton(Form_xuanzejuese)
        self.xuanze.setGeometry(QtCore.QRect(120, 250, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(45, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.xuanze.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.xuanze.setFont(font)
        self.xuanze.setObjectName(_fromUtf8("xuanze"))
        self.xiayige = QtGui.QPushButton(Form_xuanzejuese)
        self.xiayige.setGeometry(QtCore.QRect(300, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.xiayige.setFont(font)
        self.xiayige.setObjectName(_fromUtf8("xiayige"))
        self.label_8 = QtGui.QLabel(Form_xuanzejuese)
        self.label_8.setGeometry(QtCore.QRect(50, 40, 31, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.name = QtGui.QLineEdit(Form_xuanzejuese)
        self.name.setGeometry(QtCore.QRect(80, 40, 111, 20))
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setReadOnly(True)
        self.name.setObjectName(_fromUtf8("name"))
        self.label_7 = QtGui.QLabel(Form_xuanzejuese)
        self.label_7.setGeometry(QtCore.QRect(220, 40, 31, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.level = QtGui.QLineEdit(Form_xuanzejuese)
        self.level.setGeometry(QtCore.QRect(250, 40, 71, 20))
        self.level.setAlignment(QtCore.Qt.AlignCenter)
        self.level.setReadOnly(True)
        self.level.setObjectName(_fromUtf8("level"))
        self.label_10 = QtGui.QLabel(Form_xuanzejuese)
        self.label_10.setGeometry(QtCore.QRect(50, 80, 31, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gold = QtGui.QLineEdit(Form_xuanzejuese)
        self.gold.setGeometry(QtCore.QRect(80, 80, 111, 20))
        self.gold.setAlignment(QtCore.Qt.AlignCenter)
        self.gold.setReadOnly(True)
        self.gold.setObjectName(_fromUtf8("gold"))
        self.shangyige = QtGui.QPushButton(Form_xuanzejuese)
        self.shangyige.setGeometry(QtCore.QRect(30, 250, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shangyige.setFont(font)
        self.shangyige.setObjectName(_fromUtf8("shangyige"))
        self.label = QtGui.QLabel(Form_xuanzejuese)
        self.label.setGeometry(QtCore.QRect(220, 80, 21, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(185, 0, 185))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.hp = QtGui.QLineEdit(Form_xuanzejuese)
        self.hp.setGeometry(QtCore.QRect(250, 80, 71, 20))
        self.hp.setAlignment(QtCore.Qt.AlignCenter)
        self.hp.setReadOnly(True)
        self.hp.setObjectName(_fromUtf8("hp"))
        self.label_2 = QtGui.QLabel(Form_xuanzejuese)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form_xuanzejuese)
        self.label_3.setGeometry(QtCore.QRect(190, 120, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form_xuanzejuese)
        self.label_4.setGeometry(QtCore.QRect(190, 160, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form_xuanzejuese)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form_xuanzejuese)
        self.label_6.setGeometry(QtCore.QRect(190, 200, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_9 = QtGui.QLabel(Form_xuanzejuese)
        self.label_9.setGeometry(QtCore.QRect(50, 200, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.liliang = QtGui.QLineEdit(Form_xuanzejuese)
        self.liliang.setGeometry(QtCore.QRect(90, 120, 71, 20))
        self.liliang.setAlignment(QtCore.Qt.AlignCenter)
        self.liliang.setReadOnly(True)
        self.liliang.setObjectName(_fromUtf8("liliang"))
        self.jiqiao = QtGui.QLineEdit(Form_xuanzejuese)
        self.jiqiao.setGeometry(QtCore.QRect(90, 160, 71, 20))
        self.jiqiao.setAlignment(QtCore.Qt.AlignCenter)
        self.jiqiao.setReadOnly(True)
        self.jiqiao.setObjectName(_fromUtf8("jiqiao"))
        self.yili = QtGui.QLineEdit(Form_xuanzejuese)
        self.yili.setGeometry(QtCore.QRect(90, 200, 71, 20))
        self.yili.setAlignment(QtCore.Qt.AlignCenter)
        self.yili.setReadOnly(True)
        self.yili.setObjectName(_fromUtf8("yili"))
        self.fali = QtGui.QLineEdit(Form_xuanzejuese)
        self.fali.setGeometry(QtCore.QRect(230, 120, 71, 20))
        self.fali.setAlignment(QtCore.Qt.AlignCenter)
        self.fali.setReadOnly(True)
        self.fali.setObjectName(_fromUtf8("fali"))
        self.minjie = QtGui.QLineEdit(Form_xuanzejuese)
        self.minjie.setGeometry(QtCore.QRect(230, 160, 71, 20))
        self.minjie.setAlignment(QtCore.Qt.AlignCenter)
        self.minjie.setReadOnly(True)
        self.minjie.setObjectName(_fromUtf8("minjie"))
        self.xingyun = QtGui.QLineEdit(Form_xuanzejuese)
        self.xingyun.setGeometry(QtCore.QRect(230, 200, 71, 20))
        self.xingyun.setAlignment(QtCore.Qt.AlignCenter)
        self.xingyun.setReadOnly(True)
        self.xingyun.setObjectName(_fromUtf8("xingyun"))
        self.shanchu = QtGui.QPushButton(Form_xuanzejuese)
        self.shanchu.setGeometry(QtCore.QRect(210, 250, 71, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(147, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.shanchu.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shanchu.setFont(font)
        self.shanchu.setObjectName(_fromUtf8("shanchu"))

        self.retranslateUi(Form_xuanzejuese)
        QtCore.QMetaObject.connectSlotsByName(Form_xuanzejuese)

    def retranslateUi(self, Form_xuanzejuese):
        Form_xuanzejuese.setWindowTitle(_translate("Form_xuanzejuese", "Form", None))
        self.xuanze.setText(_translate("Form_xuanzejuese", "选择角色", None))
        self.xiayige.setText(_translate("Form_xuanzejuese", "下一个", None))
        self.label_8.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">角色</span></p></body></html>", None))
        self.label_7.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">等级</span></p></body></html>", None))
        self.label_10.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">金币</span></p></body></html>", None))
        self.shangyige.setText(_translate("Form_xuanzejuese", "上一个", None))
        self.label.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">HP</span></p></body></html>", None))
        self.label_2.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">力量</span></p></body></html>", None))
        self.label_3.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">法力</span></p></body></html>", None))
        self.label_4.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">敏捷</span></p></body></html>", None))
        self.label_5.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">技巧</span></p></body></html>", None))
        self.label_6.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">幸运</span></p></body></html>", None))
        self.label_9.setText(_translate("Form_xuanzejuese", "<html><head/><body><p><span style=\" color:#b900b9;\">毅力</span></p></body></html>", None))
        self.shanchu.setText(_translate("Form_xuanzejuese", "删除角色", None))

