# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small_game_weapon_ui.ui'
#
# Created: Fri Dec 04 17:54:43 2020
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_wuqidian(object):
    def setupUi(self, Form_wuqidian):
        Form_wuqidian.setObjectName(_fromUtf8("Form_wuqidian"))
        Form_wuqidian.resize(500, 330)
        Form_wuqidian.setMaximumSize(QtCore.QSize(500, 330))
        self.label = QtGui.QLabel(Form_wuqidian)
        self.label.setGeometry(QtCore.QRect(40, 50, 61, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form_wuqidian)
        self.label_2.setGeometry(QtCore.QRect(390, 50, 41, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.goumai = QtGui.QPushButton(Form_wuqidian)
        self.goumai.setGeometry(QtCore.QRect(260, 220, 75, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(188, 184, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(188, 184, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.goumai.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.goumai.setFont(font)
        self.goumai.setObjectName(_fromUtf8("goumai"))
        self.tuichu = QtGui.QPushButton(Form_wuqidian)
        self.tuichu.setGeometry(QtCore.QRect(360, 220, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tuichu.setFont(font)
        self.tuichu.setObjectName(_fromUtf8("tuichu"))
        self.mingcheng = QtGui.QComboBox(Form_wuqidian)
        self.mingcheng.setGeometry(QtCore.QRect(360, 80, 101, 22))
        self.mingcheng.setEditable(False)
        self.mingcheng.setObjectName(_fromUtf8("mingcheng"))
        self.leixing = QtGui.QComboBox(Form_wuqidian)
        self.leixing.setGeometry(QtCore.QRect(30, 80, 69, 22))
        self.leixing.setObjectName(_fromUtf8("leixing"))
        self.leixing.addItem(_fromUtf8(""))
        self.leixing.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(Form_wuqidian)
        self.label_3.setGeometry(QtCore.QRect(210, 50, 31, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pinzhi = QtGui.QComboBox(Form_wuqidian)
        self.pinzhi.setGeometry(QtCore.QRect(150, 80, 161, 22))
        self.pinzhi.setEditable(False)
        self.pinzhi.setObjectName(_fromUtf8("pinzhi"))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.pinzhi.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(Form_wuqidian)
        self.label_4.setGeometry(QtCore.QRect(330, 150, 31, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.jiage = QtGui.QLineEdit(Form_wuqidian)
        self.jiage.setGeometry(QtCore.QRect(370, 150, 81, 31))
        self.jiage.setAlignment(QtCore.Qt.AlignCenter)
        self.jiage.setReadOnly(True)
        self.jiage.setObjectName(_fromUtf8("jiage"))
        self.suijifumo = QtGui.QPushButton(Form_wuqidian)
        self.suijifumo.setGeometry(QtCore.QRect(130, 280, 75, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 87, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 87, 186))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.suijifumo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.suijifumo.setFont(font)
        self.suijifumo.setObjectName(_fromUtf8("suijifumo"))
        self.fumoxiaoguo = QtGui.QLineEdit(Form_wuqidian)
        self.fumoxiaoguo.setGeometry(QtCore.QRect(220, 280, 251, 31))
        self.fumoxiaoguo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fumoxiaoguo.setReadOnly(True)
        self.fumoxiaoguo.setObjectName(_fromUtf8("fumoxiaoguo"))
        self.label_5 = QtGui.QLabel(Form_wuqidian)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 111, 61))
        self.label_5.setLineWidth(1)
        self.label_5.setMidLineWidth(1)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form_wuqidian)
        self.label_6.setGeometry(QtCore.QRect(80, 220, 51, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gold = QtGui.QLineEdit(Form_wuqidian)
        self.gold.setGeometry(QtCore.QRect(150, 220, 81, 31))
        self.gold.setAlignment(QtCore.Qt.AlignCenter)
        self.gold.setReadOnly(True)
        self.gold.setObjectName(_fromUtf8("gold"))
        self.label_7 = QtGui.QLabel(Form_wuqidian)
        self.label_7.setGeometry(QtCore.QRect(40, 120, 41, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Form_wuqidian)
        self.label_8.setGeometry(QtCore.QRect(190, 120, 41, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Form_wuqidian)
        self.label_9.setGeometry(QtCore.QRect(40, 170, 41, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Form_wuqidian)
        self.label_10.setGeometry(QtCore.QRect(190, 170, 41, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.wugong = QtGui.QLineEdit(Form_wuqidian)
        self.wugong.setGeometry(QtCore.QRect(80, 120, 81, 31))
        self.wugong.setAlignment(QtCore.Qt.AlignCenter)
        self.wugong.setReadOnly(True)
        self.wugong.setObjectName(_fromUtf8("wugong"))
        self.fagong = QtGui.QLineEdit(Form_wuqidian)
        self.fagong.setGeometry(QtCore.QRect(80, 170, 81, 31))
        self.fagong.setAlignment(QtCore.Qt.AlignCenter)
        self.fagong.setReadOnly(True)
        self.fagong.setObjectName(_fromUtf8("fagong"))
        self.wufang = QtGui.QLineEdit(Form_wuqidian)
        self.wufang.setGeometry(QtCore.QRect(230, 120, 81, 31))
        self.wufang.setAlignment(QtCore.Qt.AlignCenter)
        self.wufang.setReadOnly(True)
        self.wufang.setObjectName(_fromUtf8("wufang"))
        self.fafang = QtGui.QLineEdit(Form_wuqidian)
        self.fafang.setGeometry(QtCore.QRect(230, 170, 81, 31))
        self.fafang.setAlignment(QtCore.Qt.AlignCenter)
        self.fafang.setReadOnly(True)
        self.fafang.setObjectName(_fromUtf8("fafang"))
        self.label_11 = QtGui.QLabel(Form_wuqidian)
        self.label_11.setGeometry(QtCore.QRect(100, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(Form_wuqidian)
        self.label_13.setGeometry(QtCore.QRect(320, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_12 = QtGui.QLabel(Form_wuqidian)
        self.label_12.setGeometry(QtCore.QRect(210, 0, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))

        self.retranslateUi(Form_wuqidian)
        QtCore.QMetaObject.connectSlotsByName(Form_wuqidian)

    def retranslateUi(self, Form_wuqidian):
        Form_wuqidian.setWindowTitle(_translate("Form_wuqidian", "Form", None))
        self.label.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">装备类型</span></p></body></html>", None))
        self.label_2.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">名称</span></p></body></html>", None))
        self.goumai.setText(_translate("Form_wuqidian", "购买", None))
        self.tuichu.setText(_translate("Form_wuqidian", "退出", None))
        self.leixing.setItemText(0, _translate("Form_wuqidian", "武器", None))
        self.leixing.setItemText(1, _translate("Form_wuqidian", "防具", None))
        self.label_3.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">品质</span></p></body></html>", None))
        self.pinzhi.setItemText(0, _translate("Form_wuqidian", "木质（无等级要求）", None))
        self.pinzhi.setItemText(1, _translate("Form_wuqidian", "铁质（10级以上可装备）", None))
        self.pinzhi.setItemText(2, _translate("Form_wuqidian", "铜质（20级以上可装备）", None))
        self.pinzhi.setItemText(3, _translate("Form_wuqidian", "银质（30级以上可装备）", None))
        self.pinzhi.setItemText(4, _translate("Form_wuqidian", "金质（40级以上可装备）", None))
        self.pinzhi.setItemText(5, _translate("Form_wuqidian", "宝石（50级以上可装备）", None))
        self.pinzhi.setItemText(6, _translate("Form_wuqidian", "珍珠（60级以上可装备）", None))
        self.pinzhi.setItemText(7, _translate("Form_wuqidian", "钻石（70级以上可装备）", None))
        self.pinzhi.setItemText(8, _translate("Form_wuqidian", "王者（80级以上可装备）", None))
        self.pinzhi.setItemText(9, _translate("Form_wuqidian", "最强王者（90级以上可装备）", None))
        self.label_4.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#acaa61;\">价格</span></p></body></html>", None))
        self.suijifumo.setText(_translate("Form_wuqidian", "随机附魔", None))
        self.label_5.setText(_translate("Form_wuqidian", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#2d24b4;\">购买后可花费300金币进行随机附魔，且耐久+20</span></p></body></html>", None))
        self.label_6.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#aba441;\">拥有金币</span></p></body></html>", None))
        self.label_7.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#b900b9;\">物攻</span></p></body></html>", None))
        self.label_8.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#b900b9;\">物防</span></p></body></html>", None))
        self.label_9.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#b900b9;\">法攻</span></p></body></html>", None))
        self.label_10.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#b900b9;\">法防</span></p></body></html>", None))
        self.label_11.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" color:#2037cc;\">武</span></p></body></html>", None))
        self.label_13.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" color:#2037cc;\">店</span></p></body></html>", None))
        self.label_12.setText(_translate("Form_wuqidian", "<html><head/><body><p><span style=\" color:#2037cc;\">器</span></p></body></html>", None))

