# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small_game_mainwindow_ui.ui'
#
# Created: Fri Dec 04 17:54:53 2020
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_main(object):
    def setupUi(self, Form_main):
        Form_main.setObjectName(_fromUtf8("Form_main"))
        Form_main.resize(680, 520)
        Form_main.setMinimumSize(QtCore.QSize(680, 520))
        Form_main.setMaximumSize(QtCore.QSize(680, 520))
        self.label = QtGui.QLabel(Form_main)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form_main)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 41, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.name = QtGui.QLineEdit(Form_main)
        self.name.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setReadOnly(True)
        self.name.setObjectName(_fromUtf8("name"))
        self.level = QtGui.QLineEdit(Form_main)
        self.level.setGeometry(QtCore.QRect(240, 20, 71, 20))
        self.level.setAlignment(QtCore.Qt.AlignCenter)
        self.level.setReadOnly(True)
        self.level.setObjectName(_fromUtf8("level"))
        self.label_3 = QtGui.QLabel(Form_main)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gold = QtGui.QLineEdit(Form_main)
        self.gold.setGeometry(QtCore.QRect(60, 50, 111, 20))
        self.gold.setAlignment(QtCore.Qt.AlignCenter)
        self.gold.setReadOnly(True)
        self.gold.setObjectName(_fromUtf8("gold"))
        self.label_4 = QtGui.QLabel(Form_main)
        self.label_4.setGeometry(QtCore.QRect(430, 20, 41, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.jihuoma = QtGui.QLineEdit(Form_main)
        self.jihuoma.setGeometry(QtCore.QRect(480, 20, 121, 20))
        self.jihuoma.setObjectName(_fromUtf8("jihuoma"))
        self.maoxian = QtGui.QPushButton(Form_main)
        self.maoxian.setGeometry(QtCore.QRect(580, 260, 81, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 198, 198))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 173, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(26, 238, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.maoxian.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.maoxian.setFont(font)
        self.maoxian.setObjectName(_fromUtf8("maoxian"))
        self.shijian = QtGui.QTextEdit(Form_main)
        self.shijian.setGeometry(QtCore.QRect(30, 230, 531, 141))
        self.shijian.setObjectName(_fromUtf8("shijian"))
        self.label_6 = QtGui.QLabel(Form_main)
        self.label_6.setGeometry(QtCore.QRect(50, 90, 21, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.hp = QtGui.QLineEdit(Form_main)
        self.hp.setGeometry(QtCore.QRect(70, 90, 71, 20))
        self.hp.setAlignment(QtCore.Qt.AlignCenter)
        self.hp.setReadOnly(True)
        self.hp.setObjectName(_fromUtf8("hp"))
        self.label_7 = QtGui.QLabel(Form_main)
        self.label_7.setGeometry(QtCore.QRect(40, 120, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.wugong = QtGui.QLineEdit(Form_main)
        self.wugong.setGeometry(QtCore.QRect(70, 120, 71, 20))
        self.wugong.setAlignment(QtCore.Qt.AlignCenter)
        self.wugong.setReadOnly(True)
        self.wugong.setObjectName(_fromUtf8("wugong"))
        self.label_8 = QtGui.QLabel(Form_main)
        self.label_8.setGeometry(QtCore.QRect(160, 120, 31, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Form_main)
        self.label_9.setGeometry(QtCore.QRect(160, 150, 31, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.wufang = QtGui.QLineEdit(Form_main)
        self.wufang.setGeometry(QtCore.QRect(190, 120, 71, 20))
        self.wufang.setAlignment(QtCore.Qt.AlignCenter)
        self.wufang.setReadOnly(True)
        self.wufang.setObjectName(_fromUtf8("wufang"))
        self.baoji = QtGui.QLineEdit(Form_main)
        self.baoji.setGeometry(QtCore.QRect(190, 150, 71, 20))
        self.baoji.setAlignment(QtCore.Qt.AlignCenter)
        self.baoji.setReadOnly(True)
        self.baoji.setObjectName(_fromUtf8("baoji"))
        self.label_10 = QtGui.QLabel(Form_main)
        self.label_10.setGeometry(QtCore.QRect(410, 120, 31, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Form_main)
        self.label_11.setGeometry(QtCore.QRect(280, 150, 31, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.fafang = QtGui.QLineEdit(Form_main)
        self.fafang.setGeometry(QtCore.QRect(450, 120, 81, 20))
        self.fafang.setAlignment(QtCore.Qt.AlignCenter)
        self.fafang.setReadOnly(True)
        self.fafang.setObjectName(_fromUtf8("fafang"))
        self.shanbi = QtGui.QLineEdit(Form_main)
        self.shanbi.setGeometry(QtCore.QRect(310, 150, 81, 20))
        self.shanbi.setAlignment(QtCore.Qt.AlignCenter)
        self.shanbi.setReadOnly(True)
        self.shanbi.setObjectName(_fromUtf8("shanbi"))
        self.label_12 = QtGui.QLabel(Form_main)
        self.label_12.setGeometry(QtCore.QRect(410, 150, 31, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Form_main)
        self.label_13.setGeometry(QtCore.QRect(160, 90, 31, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.mingzhong = QtGui.QLineEdit(Form_main)
        self.mingzhong.setGeometry(QtCore.QRect(450, 150, 81, 20))
        self.mingzhong.setAlignment(QtCore.Qt.AlignCenter)
        self.mingzhong.setReadOnly(True)
        self.mingzhong.setObjectName(_fromUtf8("mingzhong"))
        self.sudu = QtGui.QLineEdit(Form_main)
        self.sudu.setGeometry(QtCore.QRect(190, 90, 71, 20))
        self.sudu.setAlignment(QtCore.Qt.AlignCenter)
        self.sudu.setReadOnly(True)
        self.sudu.setObjectName(_fromUtf8("sudu"))
        self.shuxingjiadian = QtGui.QPushButton(Form_main)
        self.shuxingjiadian.setGeometry(QtCore.QRect(580, 120, 75, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.shuxingjiadian.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.shuxingjiadian.setFont(font)
        self.shuxingjiadian.setObjectName(_fromUtf8("shuxingjiadian"))
        self.label_14 = QtGui.QLabel(Form_main)
        self.label_14.setGeometry(QtCore.QRect(20, 400, 51, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Form_main)
        self.label_15.setGeometry(QtCore.QRect(20, 440, 51, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Form_main)
        self.label_16.setGeometry(QtCore.QRect(10, 480, 81, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.xinjian = QtGui.QPushButton(Form_main)
        self.xinjian.setGeometry(QtCore.QRect(90, 400, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.xinjian.setFont(font)
        self.xinjian.setObjectName(_fromUtf8("xinjian"))
        self.duqv = QtGui.QPushButton(Form_main)
        self.duqv.setGeometry(QtCore.QRect(90, 440, 61, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.duqv.setFont(font)
        self.duqv.setObjectName(_fromUtf8("duqv"))
        self.shanchu = QtGui.QPushButton(Form_main)
        self.shanchu.setGeometry(QtCore.QRect(90, 480, 61, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.shanchu.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.shanchu.setFont(font)
        self.shanchu.setObjectName(_fromUtf8("shanchu"))
        self.label_17 = QtGui.QLabel(Form_main)
        self.label_17.setGeometry(QtCore.QRect(290, 400, 71, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(Form_main)
        self.label_18.setGeometry(QtCore.QRect(590, 400, 71, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.wuqidian = QtGui.QPushButton(Form_main)
        self.wuqidian.setGeometry(QtCore.QRect(290, 430, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 68, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 68, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.wuqidian.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.wuqidian.setFont(font)
        self.wuqidian.setObjectName(_fromUtf8("wuqidian"))
        self.fuhuoquan = QtGui.QPushButton(Form_main)
        self.fuhuoquan.setGeometry(QtCore.QRect(590, 430, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(45, 168, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 168, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.fuhuoquan.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.fuhuoquan.setFont(font)
        self.fuhuoquan.setObjectName(_fromUtf8("fuhuoquan"))
        self.tijiao = QtGui.QPushButton(Form_main)
        self.tijiao.setGeometry(QtCore.QRect(610, 20, 51, 23))
        self.tijiao.setObjectName(_fromUtf8("tijiao"))
        self.label_19 = QtGui.QLabel(Form_main)
        self.label_19.setGeometry(QtCore.QRect(40, 150, 31, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.renxing = QtGui.QLineEdit(Form_main)
        self.renxing.setGeometry(QtCore.QRect(70, 150, 71, 20))
        self.renxing.setAlignment(QtCore.Qt.AlignCenter)
        self.renxing.setReadOnly(True)
        self.renxing.setObjectName(_fromUtf8("renxing"))
        self.label_20 = QtGui.QLabel(Form_main)
        self.label_20.setGeometry(QtCore.QRect(280, 120, 31, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.fagong = QtGui.QLineEdit(Form_main)
        self.fagong.setGeometry(QtCore.QRect(310, 120, 81, 20))
        self.fagong.setAlignment(QtCore.Qt.AlignCenter)
        self.fagong.setReadOnly(True)
        self.fagong.setObjectName(_fromUtf8("fagong"))
        self.label_21 = QtGui.QLabel(Form_main)
        self.label_21.setGeometry(QtCore.QRect(200, 50, 41, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(Form_main)
        self.label_22.setGeometry(QtCore.QRect(360, 50, 51, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.xingdongli = QtGui.QLineEdit(Form_main)
        self.xingdongli.setGeometry(QtCore.QRect(410, 50, 113, 20))
        self.xingdongli.setAlignment(QtCore.Qt.AlignCenter)
        self.xingdongli.setReadOnly(True)
        self.xingdongli.setObjectName(_fromUtf8("xingdongli"))
        self.label_23 = QtGui.QLabel(Form_main)
        self.label_23.setGeometry(QtCore.QRect(390, 400, 71, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.yaopindian = QtGui.QPushButton(Form_main)
        self.yaopindian.setGeometry(QtCore.QRect(390, 430, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(172, 41, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 41, 181))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.yaopindian.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.yaopindian.setFont(font)
        self.yaopindian.setObjectName(_fromUtf8("yaopindian"))
        self.jingyan = QtGui.QLineEdit(Form_main)
        self.jingyan.setGeometry(QtCore.QRect(240, 50, 101, 20))
        self.jingyan.setAlignment(QtCore.Qt.AlignCenter)
        self.jingyan.setReadOnly(True)
        self.jingyan.setObjectName(_fromUtf8("jingyan"))
        self.beibao = QtGui.QPushButton(Form_main)
        self.beibao.setGeometry(QtCore.QRect(180, 430, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.beibao.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.beibao.setFont(font)
        self.beibao.setObjectName(_fromUtf8("beibao"))
        self.label_24 = QtGui.QLabel(Form_main)
        self.label_24.setGeometry(QtCore.QRect(30, 190, 71, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.dangqianwuqi = QtGui.QLineEdit(Form_main)
        self.dangqianwuqi.setGeometry(QtCore.QRect(100, 190, 181, 20))
        self.dangqianwuqi.setAlignment(QtCore.Qt.AlignCenter)
        self.dangqianwuqi.setReadOnly(True)
        self.dangqianwuqi.setObjectName(_fromUtf8("dangqianwuqi"))
        self.label_25 = QtGui.QLabel(Form_main)
        self.label_25.setGeometry(QtCore.QRect(310, 190, 71, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.dangqianfangju = QtGui.QLineEdit(Form_main)
        self.dangqianfangju.setGeometry(QtCore.QRect(380, 190, 181, 20))
        self.dangqianfangju.setAlignment(QtCore.Qt.AlignCenter)
        self.dangqianfangju.setReadOnly(True)
        self.dangqianfangju.setObjectName(_fromUtf8("dangqianfangju"))
        self.xuanzezhuangbei = QtGui.QPushButton(Form_main)
        self.xuanzezhuangbei.setGeometry(QtCore.QRect(580, 180, 75, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.xuanzezhuangbei.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.xuanzezhuangbei.setFont(font)
        self.xuanzezhuangbei.setObjectName(_fromUtf8("xuanzezhuangbei"))
        self.duchang = QtGui.QPushButton(Form_main)
        self.duchang.setGeometry(QtCore.QRect(490, 430, 75, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(164, 166, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 166, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.duchang.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.duchang.setFont(font)
        self.duchang.setObjectName(_fromUtf8("duchang"))
        self.label_26 = QtGui.QLabel(Form_main)
        self.label_26.setGeometry(QtCore.QRect(500, 400, 61, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))

        self.retranslateUi(Form_main)
        QtCore.QObject.connect(self.shuxingjiadian, QtCore.SIGNAL(_fromUtf8("clicked()")), Form_main.show)
        QtCore.QMetaObject.connectSlotsByName(Form_main)

    def retranslateUi(self, Form_main):
        Form_main.setWindowTitle(_translate("Form_main", "Form", None))
        self.label.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">角色：</span></p></body></html>", None))
        self.label_2.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">等级：</span></p></body></html>", None))
        self.label_3.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">金币：</span></p></body></html>", None))
        self.label_4.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#c80812;\">礼包码</span></p></body></html>", None))
        self.jihuoma.setText(_translate("Form_main", "在此输入礼包码", None))
        self.maoxian.setText(_translate("Form_main", "冒险", None))
        self.shijian.setHtml(_translate("Form_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">点击冒险，触发事件……</span></p></body></html>", None))
        self.label_6.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">HP</span></p></body></html>", None))
        self.label_7.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">物攻</span></p></body></html>", None))
        self.label_8.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">物防</span></p></body></html>", None))
        self.label_9.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">暴击</span></p></body></html>", None))
        self.label_10.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">法防</span></p></body></html>", None))
        self.label_11.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">闪避</span></p></body></html>", None))
        self.label_12.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">命中</span></p></body></html>", None))
        self.label_13.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">速度</span></p></body></html>", None))
        self.shuxingjiadian.setText(_translate("Form_main", "属性加点", None))
        self.label_14.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600;\">新建角色</span></p></body></html>", None))
        self.label_15.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600;\">读取角色</span></p></body></html>", None))
        self.label_16.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#f8290e;\">删除当前角色</span></p></body></html>", None))
        self.xinjian.setText(_translate("Form_main", "新建", None))
        self.duqv.setText(_translate("Form_main", "读取", None))
        self.shanchu.setText(_translate("Form_main", "删除", None))
        self.label_17.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#1631e3;\">进入武器店</span></p></body></html>", None))
        self.label_18.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#24c837;\">使用复活泉</span></p></body></html>", None))
        self.wuqidian.setText(_translate("Form_main", "武器店", None))
        self.fuhuoquan.setText(_translate("Form_main", "复活泉", None))
        self.tijiao.setText(_translate("Form_main", "提交", None))
        self.label_19.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">韧性</span></p></body></html>", None))
        self.label_20.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-weight:600; color:#b900b9;\">法攻</span></p></body></html>", None))
        self.label_21.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">经验：</span></p></body></html>", None))
        self.label_22.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">行动力：</span></p></body></html>", None))
        self.label_23.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#c71096;\">进入药品店</span></p></body></html>", None))
        self.yaopindian.setText(_translate("Form_main", "药品店", None))
        self.beibao.setText(_translate("Form_main", "背包", None))
        self.label_24.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#5555ff;\">装备的武器</span></p></body></html>", None))
        self.label_25.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#5555ff;\">装备的防具</span></p></body></html>", None))
        self.xuanzezhuangbei.setText(_translate("Form_main", "选择装备", None))
        self.duchang.setText(_translate("Form_main", "赌场", None))
        self.label_26.setText(_translate("Form_main", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#bebe00;\">进入赌场</span></p></body></html>", None))

